### ISSUE TITLE
Found segmentation fault when requiring a existing file after unsetting instance of ZookeeperClient under PHP 7

### ISSUE THREAD

**Issue by Timandes** [Timandes/libzookeeper#12]
This fragment can reproduce this bug:

```
$zc = new \ZookeeperClient();
unset($zc);
require 'some-existing-file.php';
```

Env:

```
php -v
PHP 7.0.6 (cli) (built: May 25 2016 15:57:17) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

Core dump (without opcache):

```
Program terminated with signal 11, Segmentation fault.
[New process 21158]
#0  _emalloc (size=47) at /data1/src/php-7.0.6/Zend/zend_alloc.c:1295
1295                    heap->free_slot[bin_num] = p->next_free_slot;
(gdb) bt
#0  _emalloc (size=47) at /data1/src/php-7.0.6/Zend/zend_alloc.c:1295
#1  0x000000000068a714 in lex_scan (zendlval=0x7fff3e72fe10) at /data1/src/php-7.0.6/Zend/zend_string.h:121
#2  0x000000000069f0d6 in zendlex (elem=0x7fff3e7307a0) at /data1/src/php-7.0.6/Zend/zend_compile.c:1586
#3  0x0000000000682af0 in zendparse () at /data1/src/php-7.0.6/Zend/zend_language_parser.c:4225
#4  0x0000000000686a0d in compile_file (file_handle=0x7fff3e730b50, type=8) at Zend/zend_language_scanner.l:591
#5  0x00000000005914c6 in phar_compile_file (file_handle=0x7fff3e730b50, type=8) at /data1/src/php-7.0.6/ext/phar/phar.c:3322
#6  0x0000000000690a64 in compile_filename (type=8, filename=0x2ba4894681c0) at Zend/zend_language_scanner.l:647
#7  0x0000000000747aa1 in ZEND_INCLUDE_OR_EVAL_SPEC_CONST_HANDLER (execute_data=0x2ba489413030)
    at /data1/src/php-7.0.6/Zend/zend_vm_execute.h:3644
#8  0x00000000006fa868 in execute_ex (ex=<value optimized out>) at /data1/src/php-7.0.6/Zend/zend_vm_execute.h:417
#9  0x0000000000720591 in zend_execute (op_array=0x2ba48947b000, return_value=0x0) at /data1/src/php-7.0.6/Zend/zend_vm_execute.h:458
#10 0x00000000006bb418 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /data1/src/php-7.0.6/Zend/zend.c:1427
#11 0x000000000065e63e in php_execute_script (primary_file=0x7fff3e7341b0) at /data1/src/php-7.0.6/main/main.c:2494
#12 0x0000000000751942 in do_cli (argc=2, argv=0x120fb6e0) at /data1/src/php-7.0.6/sapi/cli/php_cli.c:974
#13 0x000000000075204f in main (argc=2, argv=0x120fb6e0) at /data1/src/php-7.0.6/sapi/cli/php_cli.c:1344
```

Core dump (with opcache):

```
Program terminated with signal 11, Segmentation fault.
[New process 24333]
#0  _emalloc (size=47) at /data1/src/php-7.0.6/Zend/zend_alloc.c:1295
1295                    heap->free_slot[bin_num] = p->next_free_slot;
(gdb) bt
#0  _emalloc (size=47) at /data1/src/php-7.0.6/Zend/zend_alloc.c:1295
#1  0x000000000068a714 in lex_scan (zendlval=0x7fff85be7c30) at /data1/src/php-7.0.6/Zend/zend_string.h:121
#2  0x000000000069f0d6 in zendlex (elem=0x7fff85be85c0) at /data1/src/php-7.0.6/Zend/zend_compile.c:1586
#3  0x0000000000682af0 in zendparse () at /data1/src/php-7.0.6/Zend/zend_language_parser.c:4225
#4  0x0000000000686a0d in compile_file (file_handle=0x7fff85be8c00, type=8) at Zend/zend_language_scanner.l:591
#5  0x00000000005914c6 in phar_compile_file (file_handle=0x7fff85be8c00, type=8) at /data1/src/php-7.0.6/ext/phar/phar.c:3322
#6  0x00002b9c636259e7 in opcache_compile_file (file_handle=0x7fff85be8c00, type=8, key=<value optimized out>,
    key_length=<value optimized out>, op_array_p=0x7fff85be8bb0)
    at /home/v-yanan/rpmbuild/BUILD/php-7.0.3/ext/opcache/ZendAccelerator.c:1480
#7  0x00002b9c63627a93 in persistent_compile_file (file_handle=0x7fff85be8c00, type=8)
    at /home/v-yanan/rpmbuild/BUILD/php-7.0.3/ext/opcache/ZendAccelerator.c:1786
#8  0x0000000000690a64 in compile_filename (type=8, filename=0x2b9c654581b0) at Zend/zend_language_scanner.l:647
#9  0x0000000000747aa1 in ZEND_INCLUDE_OR_EVAL_SPEC_CONST_HANDLER (execute_data=0x2b9c5fe13030)
    at /data1/src/php-7.0.6/Zend/zend_vm_execute.h:3644
#10 0x00000000006fa868 in execute_ex (ex=<value optimized out>) at /data1/src/php-7.0.6/Zend/zend_vm_execute.h:417
#11 0x0000000000720591 in zend_execute (op_array=0x2b9c5fe7c000, return_value=0x0) at /data1/src/php-7.0.6/Zend/zend_vm_execute.h:458
#12 0x00000000006bb418 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /data1/src/php-7.0.6/Zend/zend.c:1427
#13 0x000000000065e63e in php_execute_script (primary_file=0x7fff85bec260) at /data1/src/php-7.0.6/main/main.c:2494
#14 0x0000000000751942 in do_cli (argc=2, argv=0x798d6e0) at /data1/src/php-7.0.6/sapi/cli/php_cli.c:974
#15 0x000000000075204f in main (argc=2, argv=0x798d6e0) at /data1/src/php-7.0.6/sapi/cli/php_cli.c:1344
```

**Comment by Timandes** [comment]
Same issue as #13
